export const InitialValues = {
    products: [],
    deliveryMethod: 'pickup from post offices',
    paymentMethod: 'visa',
    totalPrice: '',
    phone: '',
    e_mail: '',
    country: '',
    cashEmail: '',
    city: '',
    street: '',
    house: '',
    apartment: '',
    postcode: '',
    storeAddress: '',
    card: '',
    cardDate: '',
    cardCVV: '',
    agree: false
}