export const IS_CART_OPEN = 'IS_CART_OPEN';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const REMOVE_ALL_ITEMS = 'REMOVE_ALL_ITEMS';
export const INC_ITEM = 'INC_ITEM';
export const DEC_ITEM = 'DEC_ITEM';
export const ON_CHANGE_INPUT = 'ON_CHANGE_INPUT';

export const ACTIVE_STEP = 'ORDER_FORM/ACTIVE_STEP'

export const SEND_ORDER_REQUEST = 'ORDER/REQUEST';
export const ORDER_COMPLETE = 'ORDER/COMPLETE';
export const ORDER_ERROR = 'ORDER/ERROR';
export const ORDER_VALUES = 'ORDER/VALUES';


export const SEND_COUNTRIES_REQUEST = 'COUNTRIES/SEND_REQUEST';
export const LOAD_COUNTRIES = 'COUNTRIES/LOAD_LIST';
export const IS_REQUEST_COUNTRIES_SUCCESS = 'COUNTRIES/REQUEST_SUCCESS';
export const IS_REQUEST_COUNTRIES_ERROR = 'COUNTRIES/REQUEST_ERROR';

export const SEND_CITIES_REQUEST = 'CITIES/SEND_REQUEST';
export const SEND_CITIES_SUCCESS = 'CITIES/SEND_SUCCESS';
export const SEND_CITIES_ERROR = 'CITIES/SEND_ERROR';
export const SEND_CITIES_RESPONSE = 'CITIES/SEND_RESPONSE';
export const RESET_CITIES = 'CITIES/RESET';
