export const SEND_REVIEW_REQUEST = 'SEND_REVIEW_REQUEST';
export const SEND_REVIEW_SUCCESS = 'SEND_REVIEW_SUCCESS';
export const SEND_REVIEW_ERROR = 'SEND_REVIEW_ERROR';
export const SEND_REVIEW_RESPONSE = 'SEND_REVIEW_RESPONSE';
