export const SEND_MAIL_REQUEST = 'SEND_MAIL_REQUEST';
export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS';
export const SEND_MAIL_ERROR = 'SEND_MAIL_ERROR';
export const SEND_MAIL_RESPONSE = 'SEND_MAIL_RESPONSE';
export const SEND_MAIL_REQUEST_FOOTER = 'SEND_MAIL_REQUEST_FOOTER';
export const SEND_MAIL_SUCCESS_FOOTER = 'SEND_MAIL_SUCCESS_FOOTER';
export const SEND_MAIL_ERROR_FOOTER = 'SEND_MAIL_ERROR_FOOTER';
export const SEND_MAIL_RESPONSE_FOOTER = 'SEND_MAIL_RESPONSE_FOOTER';